config/routes.rb
Rails.application.routes.draw do
  resources :wordlists
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/wordlist.rb
class Wordlist < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/wordlists_controller.rb
class WordlistsController < ApplicationController
  before_action :set_wordlist, only: %i[ show edit update destroy ]

  # GET /wordlists or /wordlists.json
  def index
    @wordlists = Wordlist.all
  end

  # GET /wordlists/1 or /wordlists/1.json
  def show
  end

  # GET /wordlists/new
  def new
    @wordlist = Wordlist.new
  end

  # GET /wordlists/1/edit
  def edit
  end

  # POST /wordlists or /wordlists.json
  def create
    @wordlist = Wordlist.new(wordlist_params)

    respond_to do |format|
      if @wordlist.save
        format.html { redirect_to @wordlist, notice: "Wordlist was successfully created." }
        format.json { render :show, status: :created, location: @wordlist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wordlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wordlists/1 or /wordlists/1.json
  def update
    respond_to do |format|
      if @wordlist.update(wordlist_params)
        format.html { redirect_to @wordlist, notice: "Wordlist was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @wordlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wordlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wordlists/1 or /wordlists/1.json
  def destroy
    @wordlist.destroy

    respond_to do |format|
      format.html { redirect_to wordlists_path, notice: "Wordlist was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wordlist
      @wordlist = Wordlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wordlist_params
      params.require(:wordlist).permit(:english_word, :japanese_ward)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wordlists_helper.rb
module WordlistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlashCard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/wordlists/_form.html.erb
<%= form_with(model: wordlist) do |form| %>
  <% if wordlist.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(wordlist.errors.count, "error") %> prohibited this wordlist from being saved:</h2>

      <ul>
        <% wordlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :english_word, style: "display: block" %>
    <%= form.text_field :english_word %>
  </div>

  <div>
    <%= form.label :japanese_ward, style: "display: block" %>
    <%= form.text_field :japanese_ward %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/wordlists/_wordlist.html.erb
<div id="<%= dom_id wordlist %>">
  <p>
    <strong>English word:</strong>
    <%= wordlist.english_word %>
  </p>

  <p>
    <strong>Japanese ward:</strong>
    <%= wordlist.japanese_ward %>
  </p>

</div>

app/views/wordlists/edit.html.erb
<h1>Editing wordlist</h1>

<%= render "form", wordlist: @wordlist %>

<br>

<div>
  <%= link_to "Show this wordlist", @wordlist %> |
  <%= link_to "Back to wordlists", wordlists_path %>
</div>

app/views/wordlists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Wordlists</h1>

<div id="wordlists">
  <% @wordlists.each do |wordlist| %>
    <%= render wordlist %>
    <p>
      <%= link_to "Show this wordlist", wordlist %>
    </p>
  <% end %>
</div>

<%= link_to "New wordlist", new_wordlist_path %>

app/views/wordlists/new.html.erb
<h1>New wordlist</h1>

<%= render "form", wordlist: @wordlist %>

<br>

<div>
  <%= link_to "Back to wordlists", wordlists_path %>
</div>

app/views/wordlists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @wordlist %>

<div>
  <%= link_to "Edit this wordlist", edit_wordlist_path(@wordlist) %> |
  <%= link_to "Back to wordlists", wordlists_path %>

  <%= button_to "Destroy this wordlist", @wordlist, method: :delete %>
</div>